<?php


namespace App\Admin\Selectable;


use App\ActiveAward;
use App\ShopGoods;
use Encore\Admin\Grid\Selectable;

class ActiveAwardSelectable extends Selectable
{
    public $model = ActiveAward::class;
    public function make()
    {
        $this->column('ActiveID');
        $this->column('Item.Name');
        $this->column('Name');
        $this->column('Count')->editable();
        $this->column('ValidDate')->editable();
        $this->column('StrengthenLevel')->editable();
        $this->column('AttackCompose')->default(0)->editable('textarea');
        $this->column('DefendCompose')->default(0)->editable();
        $this->column('LuckCompose');
        $this->column('AgilityCompose');
        $this->column('Gold');
        $this->column('Money','tieefn')->editable();
        $this->column('Sex');
        $this->column('Mark');//        $this->filter(function (Filter $filter) {
//            $filter->like('name');
//        });
    }

    protected function disableFeatures()
    {
        return $this->disableExport();
//            ->disableActions()
//            ->disableBatchActions()
//            ->disableCreateButton()
//            ->disableColumnSelector()
//            ->disablePerPageSelector();
//        return parent::disableFeatures(); // TODO: Change the autogenerated stub
    }
}
