<?php

namespace App\Admin\Forms;

use Encore\Admin\Widgets\Form;
use Illuminate\Http\Request;

class EditPlayerForm extends Form
{
private $p;
    public function __construct($player)
    {
        $this->p = $player;
    }

    /**
     * The form title.
     *
     * @var string
     */
    public $title = 'Chỉnh sửa nhân vật';

    /**
     * Handle the form request.
     *
     * @param Request $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function handle(Request $request)
    {
        //dump($request->all());

        admin_success('Processed successfully.');

        return back();
    }

    /**
     * Build a form here.
     */
    public function form()
    {

        $this->text('UserName')->rules('required');
        $this->text('Tên Nhân vật')->value($this->p->NickName);
//        $this->switch('IsConsortia')->value($this->player->IsConsortia);
//        $this->number('ConsortiaID')->value($this->player->ConsortiaID);
//        $this->radio('Giới tính')->value($this->player->Sex)->options([0 => 'Nam', 1=> 'Nữ'])->stacked();
//        $this->number('Trận thắng')->value($this->player->Win);
//        $this->number('Total')->value($this->player->Total);
//        $this->number('Kinh nghiệm (EXP)')->value($this->player->GP);
//        $this->number('Vàng')->value($this->player->Gold);
//        $this->number('Xu')->value($this->player->Money);
//        $this->number('Lễ Kim')->value($this->player->MoneyLock);
//        $this->number('Grade')->value($this->player->Grade);
//        $this->number('OnlineTime')->value($this->player->OnlineTime);
//        $this->text('ServerName')->value($this->player->ServerName);
    }

    /**
     * The data of the form.
     *
     * @return array $data
     */
    public function data()
    {
        return [
            'UserName'       => 'John Doe',
//            'email'      => 'John.Doe@gmail.com',
//            'created_at' => now(),
        ];
    }

    public function id($name, $label = ''): \Encore\Admin\Form\Field\Id
    {
        parent::id($name, $label); // TODO: Change the autogenerated stub
    }
}
